### PR TITLE
[#220] Fix: namespace and environment are misused

### LINKED ISSUE #220: Fix: namespace and environment are misused
## Issue

When reading the [definition of the 2 variables](https://github.com/nimblehq/infrastructure-templates/blob/develop/templates/terraform/core/variables.tf):

image

- namespace should be used rarely
- environment should be used in every resource for tagging and generating names

However, the code implementation reveals that we use `namespace` everywhere for tagging resources.

For this reason, we must use a namespace that includes the environment name... and an environment that includes the namespace (which reduces the flexibility to use this var).

## Expected

Given the application `my-blog`:
- namespace should be `my-blog-web`
- environment should be `staging` (or `prod`)
- the resources should be tagged with a local `"${namespace}-${environment}-some-name"`

## Steps to reproduce

1. Create or open any infra repo that use this template 😇

### PR DESCRIPTION
**Pull request by malparty**
- Close #220

## What happened 👀

- [x] move `namespace` to a local without the environment
- [x] add `env_namespace` local that includes the environment

## Insight 📝

I'm not sure about how could we add tests for this change, feel free to suggest anything 🙌 

## Proof Of Work 📹

image

### CODE REVIEW

**Comment by Nihisil** [comment]
I like this clean up 🧹 

The question is why we need `namespace` at all? I found only one usage at the moment: `"name": "${namespace}",`, and probably this usage was missed during refactoring and it should be `"name": "${env_namespace}",` in `service.json.tfpl`.

**Comment by malparty** [comment]
Nice catch @Nihisil 🙏 

a89a771 ✅ 

As for the question `do we need it at all?`, I agree we could remove it:

- before:

```
      locals {
        namespace = "app-name"
        env_namespace = "\${namespace}-\${var.environment}"
      }`;
```

- after:

```
      locals {
        env_namespace = "app-name-\${var.environment}"
      }`;
```

I've done it in 3aee9bd but feel free to let me know which way you prefer (it's quick to rollback that small change 😇). Thanks 🙌

**Comment by Nihisil** [comment]
Updated way looks great for me, I have only one remained thing. It looks like out security group is broken, it tries to read env namespace from `local`, but it should be `var`. It applies only to `/modules/security_group/main.tf` file and all other places looks good.

image

**Comment by Nihisil** [comment]
Great work 🎉 , but I brought you something new (pls don't hate me):

```
$ terraform validate
╷
│ Error: Invalid function argument
│
│   on ../modules/ecs/main.tf line 35, in locals:
│   35:   container_definitions = templatefile("${path.module}/service.json.tftpl", local.container_vars)
│     ├────────────────
│     │ while calling templatefile(path, vars)
│     │ local.container_vars is object with 13 attributes
│
│ Invalid value for "vars" parameter: vars map does not contain key "namespace", referenced at
│ ../modules/ecs/service.json.tftpl:19,37-46.
```

**Comment by hoangmirs** [comment]
> Great work 🎉 , but I brought you something new (pls don't hate me):
> 
> ```
> $ terraform validate
> ╷
> │ Error: Invalid function argument
> │
> │   on ../modules/ecs/main.tf line 35, in locals:
> │   35:   container_definitions = templatefile("${path.module}/service.json.tftpl", local.container_vars)
> │     ├────────────────
> │     │ while calling templatefile(path, vars)
> │     │ local.container_vars is object with 13 attributes
> │
> │ Invalid value for "vars" parameter: vars map does not contain key "namespace", referenced at
> │ ../modules/ecs/service.json.tftpl:19,37-46.
> ```

@malparty This might be the last place that we need to change 👉 https://github.com/nimblehq/infrastructure-templates/blob/develop/templates/addons/aws/modules/ecs/service.json.tftpl#L19

**Review by hoangmirs — APPROVED** [review]

**Review by longnd — APPROVED** [review]

**Review by Nihisil — APPROVED** [review]
Thanks!

**Pull request merged**
