### PR TITLE
[#104] Improve the way to manage environment variables and secrets

### LINKED ISSUE #104: Improve the way to manage environment variables and secrets
## Why
With the current structure, every time we need to add a new environment variable, we need to open a PR to define a new variable and add it into the container definition([example](https://github.com/worpt-wallet/wallet-infra/pull/62)). That is tedious.
Inspired by the Varun project, we set a new way to do so in EWA Payroll project: maintain a new variable `environment_variables` on Terraform cloud as a JSON object; a new variable just needs to add to it.
A similar approach (but less flexible) for secrets. These PRs can be used as references.
https://github.com/onward-venture/ewa-payroll-infra/pull/2
https://github.com/onward-venture/ewa-payroll-infra/pull/6
Wiki: https://github.com/worpt-wallet/wallet-api/wiki/Environment-Variables

## Who benefits
All developers who need to occasionally define new environment variables and secrets when working on the tasks.

### PR DESCRIPTION
**Pull request by hoangmirs**
- Close #104 

## What happened 👀

- Refactor how to add environment variables to ECS Task. Now we just need to update the list of environment variables in a variable.
- Refactor the SSM module to reduce work when adding a new secret variable. Now we just need to create a new variable in the main `variables.tf` file, then add it to the secrets object in the SSM module.

## Insight 📝

- Reference from EWA project.
- Still keep using SSM instead of Secret manager as we don't need to rotate the secret right now.

## Proof Of Work 📹

N/A

### CODE REVIEW

**Comment by malparty** [comment]
Should we add some documentation for these 2 tasks (add env. var, add secret)? 🤔 
Maybe it's a good opportunity to create a Wiki for the infra template? 😇 

Thanks

**Comment by hoangmirs** [comment]
> Should we add some documentation for these 2 tasks (add env. var, add secret)? 🤔 Maybe it's a good opportunity to create a Wiki for the infra template? 😇

Yes, we should, but for now, we haven't started building them, then I'm not sure where should we put the documentation.
We had 2 issues related to this, and we should start on them soon:
- https://github.com/nimblehq/infrastructure-templates/issues/46
- https://github.com/nimblehq/infrastructure-templates/issues/123

**Comment by malparty** [comment]
@hoangmirs there is already some documentation in the AWS Readme.md (`skeleton/aws/README.md`).

As your current change is "Fresh", what about just adding 1 section to this file and handling the "big documentation refactor into a wiki" in another task? 🤔 

https://github.com/nimblehq/infrastructure-templates/pull/83/files#diff-e0a2a5a9d28ec8cd73a6cfc9dc6c883b2d9c150c3dd609b40bbff2af3fdcdd2f

**Comment by hoangmirs** [comment]
> @hoangmirs there is already some documentation in the AWS Readme.md (`skeleton/aws/README.md`).
> 
> As your current change is "Fresh", what about just adding 1 section to this file and handling the "big documentation refactor into a wiki" in another task? 🤔
> 
> https://github.com/nimblehq/infrastructure-templates/pull/83/files#diff-e0a2a5a9d28ec8cd73a6cfc9dc6c883b2d9c150c3dd609b40bbff2af3fdcdd2f

Thanks for reminding me, added in https://github.com/nimblehq/infrastructure-templates/pull/121/commits/6bc234a1e06df507d56b3dbe94a166c5480215cf with the content from `ewa-payroll-web` :D

**Review by malparty — APPROVED** [review]
LGTM!

**Review by longnd — APPROVED** [review]

**Pull request merged**
